#!/usr/bin/env python3
"""Bootstrap a mapping tree around a dropped-in ROM (phase 0).

Generates the minimal byte-identity harness — written from first
principles for this project (nothing borrowed from decomp skeletons;
mapping needs no C toolchain, no charmap, no data extraction):

  asm/macros.inc   arm/thumb function bracket macros
  asm/rom.s        the whole image as one .incbin
  linker.ld        single .text at 0x08000000, objects in address order
  Makefile         as -> ld -> objcopy -> sha256 compare
  <rom>.sha256     the pinned hash

After this, `make check` passes by construction and the peel loop
(tools/peel.py) takes over. The generated files are derived-tree
plumbing, not content: the only image bytes anywhere are in the
user's own ROM, referenced by .incbin.

Usage:
  python3 tools/setup.py [--tree DIR] [--rom NAME.gba]
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from peel import find_rom

MACROS = """\
@ Function bracket macros for peeled disassembly. Each marks the symbol
@ global, typed, and sized so the ELF carries the map (the seed/emit
@ tools read it back out with readelf).

        .macro arm_func_start name
        .align 2, 0
        .global \\name
        .type \\name, function
        .arm
        .endm

        .macro arm_func_end name
        .size \\name, . - \\name
        .endm

        .macro thumb_func_start name
        .align 1, 0
        .global \\name
        .type \\name, function
        .thumb
        .thumb_func
        .endm

        .macro thumb_func_end name
        .size \\name, . - \\name
        .endm
"""

MAKEFILE = """\
# Generated by tools/setup.py — the byte-identity oracle.
# `make check` must pass after every peel; that is the whole contract.

ROM      := {rom}
TARGET   := build/rebuilt.gba
PREFIX   ?= arm-none-eabi-
ASFLAGS  := -mcpu=arm7tdmi -EL -I .

ASMSRCS  := $(shell find asm -name '*.s' | sort)
OBJS     := $(ASMSRCS:%.s=build/%.o)

all: $(TARGET)

build/%.o: %.s asm/macros.inc
\t@mkdir -p $(dir $@)
\t$(PREFIX)as $(ASFLAGS) -o $@ $<

build/rebuilt.elf: $(OBJS) linker.ld
\t$(PREFIX)ld -T linker.ld -o $@

$(TARGET): build/rebuilt.elf
\t$(PREFIX)objcopy -O binary $< $@

check: $(TARGET)
\t@python3 -c "import hashlib,sys; \\
got = hashlib.sha256(open('$(TARGET)','rb').read()).hexdigest(); \\
want = open('$(ROM).sha256').read().split()[0]; \\
print('$(TARGET):', 'OK' if got == want else 'SHA256 MISMATCH'); \\
sys.exit(0 if got == want else 1)"

clean:
\trm -rf build

.PHONY: all check clean
"""

LINKER = """\
/* Generated by tools/setup.py. Every object is listed explicitly, in
 * ROM address order — the map is address-truth, nothing ever shifts.
 * Peels insert their build/asm/disasm_*.o line at the right spot and
 * shrink the surrounding incbin. */
ENTRY(_rom_start)
SECTIONS
{{
    . = 0x08000000;
    .text :
    {{
        build/asm/rom.o(.text)
    }}
    /DISCARD/ : {{ *(.ARM.attributes) *(.comment) *(.note*) }}
}}
"""

ROM_S = """\
@ Generated by tools/setup.py. Phase 0: the whole image, unpeeled.
@ Peels carve [start, end) out of this by splitting the .incbin.

        .global _rom_start
_rom_start:
        .incbin "{rom}", 0x0, {size:#x}
"""


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--tree", type=Path, default=Path("."))
    p.add_argument("--rom", help="ROM file name (default: auto-detect)")
    a = p.parse_args()

    tree = a.tree.resolve()
    rom = find_rom(tree, a.rom)
    size = rom.stat().st_size
    sha = hashlib.sha256(rom.read_bytes()).hexdigest()

    for rel in ("Makefile", "linker.ld", "asm/rom.s", "asm/macros.inc"):
        if (tree / rel).exists():
            print(f"ERROR: {rel} already exists — this tree is already set up "
                  "(remove the harness first to re-bootstrap)", file=sys.stderr)
            return 1

    (tree / "asm").mkdir(exist_ok=True)
    (tree / "asm/macros.inc").write_text(MACROS)
    (tree / "asm/rom.s").write_text(ROM_S.format(rom=rom.name, size=size))
    (tree / "linker.ld").write_text(LINKER.format())
    (tree / "Makefile").write_text(MAKEFILE.format(rom=rom.name))
    (tree / f"{rom.name}.sha256").write_text(f"{sha}  {rom.name}\n")

    print(f"bootstrapped {tree} around {rom.name} ({size} bytes, sha256 {sha[:16]}…)")
    print("next: make check   (must pass by construction)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
