#!/usr/bin/env python3
"""Wire a peeled function into the build: split the covering .incbin
and insert the linker entry. The deterministic 90% of peel step 3.

Model: some .s file under asm/ contains `.incbin "<rom>", OFF, LEN`
covering [start, end). This tool
  1. replaces it with a head incbin [OFF, start) in place (dropped if
     empty),
  2. emits a tail `asm/raw_0xEND.s` holding [end, OFF+LEN) (skipped if
     empty),
  3. inserts the peeled object and the tail object into the linker
     script right after the covering file's entry (or replaces it when
     the head vanished),
and prints what it did. It exits 3 with a diagnosis when the tree
doesn't match this model (hand-written linker layouts, incbins it
can't find) — that's the signal for a human/agent to wire by hand.
`make check` afterwards is still the caller's job; this tool edits,
it doesn't prove.

Usage:
  python3 tools/wire.py --tree . --start 0x08001234 --end 0x08001268
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from peel import find_rom

ROM_BASE = 0x08000000


def obj_for(tree: Path, src: Path) -> str:
    return f"build/{src.relative_to(tree)}".replace(".s", ".o")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--tree", type=Path, default=Path("."))
    p.add_argument("--rom")
    p.add_argument("--start", required=True, type=lambda s: int(s, 0))
    p.add_argument("--end", required=True, type=lambda s: int(s, 0))
    a = p.parse_args()

    tree = a.tree.resolve()
    rom = find_rom(tree, a.rom)
    s_off, e_off = a.start - ROM_BASE, a.end - ROM_BASE

    inc_re = re.compile(
        r'^(\s*)\.incbin\s+"' + re.escape(rom.name) + r'"\s*,\s*(0[xX][0-9a-fA-F]+|\d+)\s*,\s*(0[xX][0-9a-fA-F]+|\d+)\s*$'
    )

    covering = None
    for src in sorted(tree.glob("asm/**/*.s")):
        # Peel outputs incbin their own range; only blob holders count.
        if src.name.startswith("disasm_"):
            continue
        for ln, line in enumerate(src.read_text().splitlines()):
            m = inc_re.match(line)
            if not m:
                continue
            off, length = int(m.group(2), 0), int(m.group(3), 0)
            if off <= s_off and e_off <= off + length:
                covering = (src, ln, m.group(1), off, length)
                break
        if covering:
            break
    if not covering:
        print(f"wire: no .incbin of {rom.name} covering [{a.start:#x}, {a.end:#x}) "
              "found under asm/ — wire by hand", file=sys.stderr)
        return 3

    src, ln, indent, off, length = covering
    lines = src.read_text().splitlines()
    head_len = s_off - off
    tail_len = off + length - e_off

    peeled_obj = f"build/asm/disasm_{a.start:#010x}.o"
    if not (tree / f"asm/disasm_{a.start:#010x}.s").exists():
        print(f"wire: asm/disasm_{a.start:#010x}.s missing — peel first", file=sys.stderr)
        return 3

    # Validate EVERYTHING before mutating anything — a half-wired tree
    # is worse than a refusal (a partial edit once silently dropped a
    # peel's incbin and only make check caught it downstream).
    tail_src = tree / f"asm/raw_{a.end:#010x}.s" if tail_len > 0 else None
    if tail_src is not None and tail_src.exists():
        print(f"wire: {tail_src} already exists — wire by hand", file=sys.stderr)
        return 3
    ld = tree / "linker.ld"
    if not ld.is_file():
        print("wire: no linker.ld — wire by hand", file=sys.stderr)
        return 3
    cov_obj = obj_for(tree, src)
    text = ld.read_text().splitlines()
    hits = [i for i, l in enumerate(text) if cov_obj in l]
    if len(hits) != 1:
        print(f"wire: {cov_obj} appears {len(hits)} times in linker.ld — wire by hand",
              file=sys.stderr)
        return 3

    # 1. head: shrink in place (or drop the line).
    if head_len > 0:
        lines[ln] = f'{indent}.incbin "{rom.name}", {off:#x}, {head_len:#x}'
    else:
        del lines[ln]
    src.write_text("\n".join(lines) + ("\n" if lines else ""))

    # 2. tail: its own raw object so the peeled object can sit between.
    tail_obj = None
    if tail_src is not None:
        tail_src.write_text(
            f"@ Generated by tools/wire.py: unpeeled residue after {a.end:#010x}.\n\n"
            f'        .incbin "{rom.name}", {e_off:#x}, {tail_len:#x}\n'
        )
        tail_obj = obj_for(tree, tail_src)

    # 3. linker: insert after (or replace) the covering object's entry.
    i = hits[0]
    lindent = re.match(r"\s*", text[i]).group(0)
    inserts = [f"{lindent}{peeled_obj}(.text)"]
    if tail_obj:
        inserts.append(f"{lindent}{tail_obj}(.text)")
    if head_len > 0:
        text[i + 1 : i + 1] = inserts
    else:
        text[i : i + 1] = inserts
    ld.write_text("\n".join(text) + "\n")

    print(f"wired [{a.start:#x}, {a.end:#x}): head {head_len:#x} bytes in "
          f"{src.relative_to(tree)}, peeled obj {'+ tail ' + tail_obj if tail_obj else ''}"
          f"into linker.ld — now run `make check`")
    return 0


if __name__ == "__main__":
    sys.exit(main())
